name: inserter
description: Additional tooling for mason_cli to write to existing files.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  apealed_analysis: ^0.0.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

dependencies:
