name: inserter
description: Tooling for inserting String into Files given their respective strategies.
version: 0.2.0
repository: https://github.com/Luckey-Elijah/inserter

environment:
  sdk: ">=3.4.0 <4.0.0"

dev_dependencies:
  mocktail: ">=0.3.0 <2.0.0"
  test: ^1.19.2
  very_good_analysis: ^6.0.0

dependencies:
  args: ^2.5.0
  mason_logger: ^0.3.1

executables:
  inserter:
